/*
 * File: app/view/BandList.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.BandList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.bandlist',

    config: {
        store: 'MyStore',
        onItemDisclosure: true,
        itemTpl: [
            '<div>{Name}</div>'
        ],
        listeners: [
            {
                fn: 'onListItemTap',
                event: 'itemtap'
            }
        ]
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        var main = Ext.getCmp('main'),
            toolbar = main.getComponent('toolbar'),
            back = toolbar.getComponent('backButton'),
            detail = Ext.ComponentQuery.query('#bandDetail')[0] || Ext.create('MyApp.view.BandDetail',{hidden: true}),
            bandImage = detail.getComponent('bandImage'),
            description = detail.getComponent('description');

        bandImage.setSrc(record.data.Image);
        description.setHtml(record.data.Bio);
        toolbar.setTitle(record.data.Name);

        back.show();
        main.add(detail);
        detail.show();
    }

});