/*
 * File: app/view/BandDetail.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.BandDetail', {
    extend: 'Ext.Container',

    config: {
        itemId: 'bandDetail',
        hideAnimation: {
            type: 'slideOut',
            direction: 'right',
            reveal: true
        },
        showAnimation: {
            type: 'slideIn',
            direction: 'left',
            cover: true
        },
        scrollable: {
            directionLock: true,
            direction: 'vertical'
        },
        items: [
            {
                xtype: 'image',
                height: 300,
                hidden: true,
                itemId: 'bandImage',
                showAnimation: 'fadeIn',
                width: '100%'
            },
            {
                xtype: 'container',
                itemId: 'description',
                padding: 10
            }
        ],
        listeners: [
            {
                fn: 'onBandImageLoad',
                event: 'load',
                delegate: '#bandImage'
            },
            {
                fn: 'onContainerInitialize',
                event: 'initialize'
            }
        ]
    },

    onBandImageLoad: function(image, e, eOpts) {
        image.show();
    },

    onContainerInitialize: function(component, eOpts) {
        Ext.ComponentQuery.query('#backButton')[0].show();
        MyApp.app.setDragInteraction(component);
    }

});