/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Main', {
    extend: 'Ext.Container',

    requires: [
        'MyApp.view.BandList'
    ],

    config: {
        id: 'main',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                itemId: 'toolbar',
                title: 'Krautrock',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        hideAnimation: 'fadeOut',
                        itemId: 'backButton',
                        showAnimation: {
                            type: 'slide',
                            direction: 'right'
                        },
                        ui: 'back',
                        text: 'Krautrock'
                    }
                ]
            },
            {
                xtype: 'bandlist'
            }
        ],
        listeners: [
            {
                fn: 'onBackButtonTap',
                event: 'tap',
                delegate: '#backButton'
            }
        ]
    },

    onBackButtonTap: function(button, e, eOpts) {
        Ext.ComponentQuery.query('#bandDetail')[0].hide();
        Ext.ComponentQuery.query('#toolbar')[0].setTitle('Krautrock');
        button.hide();
    }

});